### ISSUE TITLE
demo编译失败

### ISSUE THREAD

**Issue by zhuguangqiang** [Hsintao/pfld-ncnn#3]
ncnn和facedetect库函数找不到：
detect-image-demo.cpp:21: undefined reference to `ncnn::Mat::from_pixels_resize(unsigned char const*, int, int, int, int, int, ncnn::Allocator*)'
detect-image-demo.cpp:103: undefined reference to `facedetect_cnn(unsigned char*, unsigned char*, int, int, int)'
，仓库里提供的2个静态库有问题？

**Comment by Hsintao** [comment]
> ncnn和facedetect库函数找不到：
> detect-image-demo.cpp:21: undefined reference to `ncnn::Mat::from_pixels_resize(unsigned char const*, int, int, int, int, int, ncnn::Allocator*)' detect-image-demo.cpp:103: undefined reference to `facedetect_cnn(unsigned char*, unsigned char*, int, int, int)'
> ，仓库里提供的2个静态库有问题？

你得自己编译出静态库放到对应目录

**Comment by zhuguangqiang** [comment]
facedetect源文件是来自哪里？

**Comment by Hsintao** [comment]
> facedetect源文件是来自哪里？

https://github.com/ShiqiYu/libfacedetection
